var express = require('express');
var bodyParser = require('body-parser');
var session = require('express-session');
var passport = require('passport');
var localStrategy = require('passport-local').Strategy;
var postsRouters = require('./posts-router');
var categRouters = require('./categ-router');
var commentRouters = require('./comment-router');
var tagRouters = require('./tag-router');
var userRouters = require('./user-router');
// start an express app
var app = express();
app.use(bodyParser.json());
app.use(session({secret:"this-is-a-secret-token", resave: "true", saveUninitialized: "false"}));
app.use(passport.initialize());
app.use(passport.session());
postsRouters(app, express, passport, localStrategy);
categRouters(app);
commentRouters(app);
tagRouters(app);
userRouters(app, express, passport, localStrategy);
app.listen(8000);